export MarkedDynkinType
export marked_nodes, unmarked_nodes, levi_type, levi_rank, central_rank
export is_borel
export central_scaling_factor
export decomposition_matrix, decomposition_matrix_inv
export levi_permutation
export marked_dynkin_diagram
export is_exceptional_type

"""
    MarkedDynkinType(DT::Type{<:DynkinType}, marked)

Runtime description of a partial flag variety ``\\mathrm{G}/\\mathrm{P}``, given by a Dynkin type
`DT` and the tuple of marked simple roots defining the parabolic subgroup ``\\mathrm{P}``.

The marked nodes are stored as runtime data rather than type parameters, while
derived invariants such as the Levi type, decomposition matrix, and dimension
are cached on first use.

# Examples
```jldoctest
julia> using PartialFlagVarieties

julia> mdt = MarkedDynkinType(TypeA{4}, (2,));

julia> marked_nodes(mdt)
(2,)

julia> unmarked_nodes(mdt)
(1, 3, 4)
```
"""
struct MarkedDynkinType
  dynkin::DataType
  marked::Tuple{Vararg{Int}}

  function MarkedDynkinType(dynkin::DataType, marked::Tuple{Vararg{Int}})
    dynkin <: DynkinType || throw(ArgumentError("Expected a Dynkin type, got $dynkin"))
    dynkin = _canonical_dynkin_type(dynkin)

    R = rank(dynkin)
    for m in marked
      1 <= m <= R || throw(
        ArgumentError(
          "Marked node $m is out of range for $(Semisimple._type_name(dynkin)) (rank $R)"
        ),
      )
    end

    issorted(marked) || throw(ArgumentError("Marked nodes must be sorted, got $marked"))
    length(unique(marked)) == length(marked) || throw(ArgumentError(
      "Marked nodes must be distinct, got $marked"
    ))

    new(dynkin, marked)
  end
end

_canonical_dynkin_type(::Type{DT}) where {DT<:SimpleDynkinType} = DT

function _canonical_dynkin_type(::Type{DT}) where {DT<:ProductDynkinType}
  factors = DataType[]
  for factor in DT.parameters[1].parameters
    canonical = _canonical_dynkin_type(factor)
    if canonical <: SimpleDynkinType
      push!(factors, canonical)
    else
      append!(factors, canonical.parameters[1].parameters)
    end
  end
  ProductDynkinType{Tuple{factors...}}
end

function MarkedDynkinType(::Type{DT}, marked::Tuple{Vararg{Int}}) where {DT<:DynkinType}
  marked_int = Tuple(sort(collect(marked)))
  invoke(MarkedDynkinType, Tuple{DataType,Tuple{Vararg{Int}}}, DT, marked_int)
end

function MarkedDynkinType(::Type{DT}, marked::Tuple) where {DT<:DynkinType}
  marked_int = Tuple(sort!(collect(Int, marked)))
  invoke(MarkedDynkinType, Tuple{DataType,Tuple{Vararg{Int}}}, DT, marked_int)
end

MarkedDynkinType(::Type{DT}, marked::Vector{<:Integer}) where {DT<:DynkinType} =
  MarkedDynkinType(DT, Tuple(marked))

MarkedDynkinType(::Type{DT}, marked::Integer) where {DT<:DynkinType} = MarkedDynkinType(
  DT, (Int(marked),)
)

struct _MarkedDynkinData
  unmarked::Tuple{Vararg{Int}}
  levi::Union{Nothing,DataType}
  levi_permutation::Tuple{Vararg{Int}}
  central_scaling_factor::Int
  decomposition_matrix::Matrix{Rational{Int}}
  decomposition_matrix_inv::Matrix{Rational{Int}}
  dimension::Int
end

const _marked_dynkin_cache = let b = _default_cache_budget()
  LRU{MarkedDynkinType,_MarkedDynkinData}(;
    maxsize=_cache_maxsize(b, _DEFAULT_STRUCTURAL_FRAC * 0.4),
    by=Base.summarysize,
  )
end

function _compute_marked_dynkin_data(mdt::MarkedDynkinType)
  DT = dynkin_type(mdt)
  marked = marked_nodes(mdt)
  R = rank(DT)

  unmarked = Tuple(i for i in 1:R if !(i in marked))
  if isempty(unmarked)
    levi = nothing
    perm = ()
  else
    C = Semisimple._cartan_matrix_data(DT)
    idx = collect(unmarked)
    C_sub = C[idx, idx]
    ct = cartan_type(C_sub)
    levi = _cartan_type_to_dynkin_type(ct)
    _, ord = cartan_type_with_ordering(C_sub)
    perm = Tuple(idx[ord])
  end

  Cinv = cartan_matrix_inverse(DT)
  scaling = reduce(lcm, (denominator(Cinv[j, k]) for j in marked for k in 1:R); init=1)

  M = zeros(Rational{Int}, R, R)
  for i in unmarked
    M[i, i] = 1
  end
  for j in marked
    M[j, :] = Cinv[j, :]
  end

  Minv = inv(M)
  n_pos_G = n_positive_roots(DT)
  n_pos_L = levi === nothing ? 0 : n_positive_roots(levi)

  _MarkedDynkinData(unmarked, levi, perm, scaling, M, Minv, n_pos_G - n_pos_L)
end

_mdt_data(mdt::MarkedDynkinType) =
  get!(_marked_dynkin_cache, mdt) do
    _compute_marked_dynkin_data(mdt)
  end

"""
    dynkin_type(mdt::MarkedDynkinType) -> Type{<:DynkinType}

Return the ambient Dynkin type of `mdt` (e.g. `TypeA{4}` for ``\\mathrm{A}_4``).
"""
dynkin_type(mdt::MarkedDynkinType) = mdt.dynkin

"""
    marked_nodes(mdt::MarkedDynkinType) -> Tuple{Vararg{Int}}

Return the tuple of marked simple root indices defining the parabolic
subgroup ``\\mathrm{P}``. In the convention used by this package, marked nodes are
the *crossed-out* nodes of the Dynkin diagram: the parabolic ``\\mathrm{P}_I`` is
generated by ``\\mathrm{B}`` and ``\\mathrm{U}_{-\\alpha_j}`` for ``j \\notin I``.
"""
marked_nodes(mdt::MarkedDynkinType) = mdt.marked

"""
    unmarked_nodes(mdt::MarkedDynkinType) -> Tuple{Vararg{Int}}

Return the complement of [`marked_nodes`](@ref), i.e. the simple root
indices that span the Dynkin diagram of the semisimple Levi factor
``[\\mathrm{L}, \\mathrm{L}]``. These are the *uncrossed* nodes.
"""
unmarked_nodes(mdt::MarkedDynkinType) = _mdt_data(mdt).unmarked

"""
    central_rank(mdt::MarkedDynkinType) -> Int

Return the rank of the center ``\\operatorname{Z}(\\mathrm{L})^\\circ`` of the Levi factor, equal to
the number of marked nodes ``|I|``. This also equals the Picard rank
``\\mathrm{rk}\\,\\mathrm{Pic}(\\mathrm{G}/\\mathrm{P}_I)``.
"""
central_rank(mdt::MarkedDynkinType) = length(marked_nodes(mdt))

"""
    levi_type(mdt::MarkedDynkinType) -> Union{Nothing, Type{<:DynkinType}}

Return the Dynkin type of the semisimple part ``[\\mathrm{L}, \\mathrm{L}]`` of the Levi factor,
or `nothing` when all nodes are marked (the full flag variety ``\\mathrm{G}/\\mathrm{B}``, where
``\\mathrm{L} = T`` is a maximal torus and ``[\\mathrm{L}, \\mathrm{L}]`` is trivial).
"""
levi_type(mdt::MarkedDynkinType) = _mdt_data(mdt).levi

"""
    levi_rank(mdt::MarkedDynkinType) -> Int

Return the rank of the semisimple Levi factor ``[\\mathrm{L}, \\mathrm{L}]``, i.e. the number
of unmarked nodes.
"""
levi_rank(mdt::MarkedDynkinType) = length(unmarked_nodes(mdt))

"""
    is_borel(mdt::MarkedDynkinType) -> Bool

Return `true` if `mdt` encodes a full flag variety ``\\mathrm{G}/\\mathrm{B}`` (all nodes
marked, so ``\\mathrm{P} = \\mathrm{B}`` is the Borel subgroup).
"""
is_borel(mdt::MarkedDynkinType) = isempty(unmarked_nodes(mdt))

"""
    levi_permutation(mdt::MarkedDynkinType) -> Tuple{Vararg{Int}}

Return the unmarked nodes in the Bourbaki order of the Levi type: the ``j``-th entry is
the node of the ambient diagram playing the role of the ``j``-th simple root of
[`levi_type`](@ref).

This is the natural order of the unmarked nodes for types ``\\mathrm{A}``,
``\\mathrm{B}``, and ``\\mathrm{C}``, but not for types ``\\mathrm{D}`` and
``\\mathrm{E}``, where the sub-diagram nodes need not appear in canonical order within
the ambient diagram.
"""
levi_permutation(mdt::MarkedDynkinType) = _mdt_data(mdt).levi_permutation

"""
    central_scaling_factor(mdt::MarkedDynkinType) -> Int

Return the positive integer that clears all denominators in the marked
rows of the [`decomposition_matrix`](@ref). This is the LCM of the
denominators of the entries ``C^{-1}_{jk}`` for ``j \\in I`` (marked
nodes) and all ``k``.

Used internally to work with integer-scaled central characters instead of
rationals.
"""
central_scaling_factor(mdt::MarkedDynkinType) = _mdt_data(mdt).central_scaling_factor

"""
    decomposition_matrix(mdt::MarkedDynkinType) -> Matrix{Rational{Int}}

Return the change-of-basis matrix from ambient fundamental weights to
central-plus-Levi coordinates. Unmarked rows are the identity and marked rows
are the corresponding rows of the inverse Cartan matrix.
"""
@inline decomposition_matrix(mdt::MarkedDynkinType) = _mdt_data(mdt).decomposition_matrix

"""
    decomposition_matrix_inv(mdt::MarkedDynkinType) -> Matrix{Rational{Int}}

Return the inverse of the [`decomposition_matrix`](@ref), converting from
central-plus-Levi coordinates back to ambient fundamental weight
coordinates.
"""
@inline decomposition_matrix_inv(mdt::MarkedDynkinType) =
  _mdt_data(mdt).decomposition_matrix_inv

rank(mdt::MarkedDynkinType) = rank(dynkin_type(mdt))

"""
    dimension(mdt::MarkedDynkinType) -> Int

Return ``\\dim(\\mathrm{G}/\\mathrm{P}) = |\\Phi_{\\mathrm{G}}^+| - |\\Phi_{\\mathrm{L}}^+|``, the number of positive
roots of ``\\mathrm{G}`` minus the number of positive roots of the Levi subalgebra.
"""
dimension(mdt::MarkedDynkinType) = _mdt_data(mdt).dimension

function _nonparabolic_height(α_vec::AbstractVector{<:Integer}, marked::Tuple{Vararg{Int}})
  sum((α_vec[m] for m in marked); init=0)
end

"""
    positive_nonparabolic_roots(mdt::MarkedDynkinType) -> Vector

Return all positive roots of the ambient Lie algebra that have positive
coefficient on at least one marked simple root (i.e., the roots not in the
Levi subalgebra). These span the tangent directions of ``\\mathrm{G}/\\mathrm{P}``.
"""
function positive_nonparabolic_roots(mdt::MarkedDynkinType)
  RS = RootSystem(dynkin_type(mdt))
  filter(
    α -> _nonparabolic_height(coefficients(α), marked_nodes(mdt)) > 0,
    collect(positive_roots(RS)),
  )
end

"""
    positive_parabolic_roots(mdt::MarkedDynkinType) -> Vector

Return all positive roots of the ambient Lie algebra that have zero coefficient
on every marked simple root (i.e., the positive roots of the Levi subalgebra).
"""
function positive_parabolic_roots(mdt::MarkedDynkinType)
  RS = RootSystem(dynkin_type(mdt))
  filter(
    α -> _nonparabolic_height(coefficients(α), marked_nodes(mdt)) == 0,
    collect(positive_roots(RS)),
  )
end

"""
    tangent_weights(mdt::MarkedDynkinType) -> Vector{WeightLatticeElem}

Return the highest weights of the irreducible Levi-module decomposition of the
tangent space ``\\mathrm{T}_{eP}(\\mathrm{G}/\\mathrm{P})`` at the base point. Each weight corresponds to
a Levi-orbit of nonparabolic positive roots.
"""
function tangent_weights(mdt::MarkedDynkinType)
  RS = RootSystem(dynkin_type(mdt))
  nonpar_roots = positive_nonparabolic_roots(mdt)
  simple_parabolic = [simple_root(RS, i) for i in unmarked_nodes(mdt)]
  nonpar_set = Set(coefficients(α) for α in nonpar_roots)

  # A nonparabolic root is a highest weight for the Levi action when no
  # simple parabolic root can be added to it within the nonparabolic roots.
  highest = filter(nonpar_roots) do α
    α_coeffs = coefficients(α)
    !any(s -> (α_coeffs + coefficients(s)) in nonpar_set, simple_parabolic)
  end
  WeightLatticeElem[WeightLatticeElem(α) for α in highest]
end

function Base.show(io::IO, mdt::MarkedDynkinType)
  print(
    io, "$(Semisimple._type_name(dynkin_type(mdt))) / P_{$(join(marked_nodes(mdt), ","))}"
  )
end

"""
    marked_dynkin_diagram(mdt::MarkedDynkinType) -> String

Return an ASCII art string representation of the Dynkin diagram of `mdt` with
the marked nodes highlighted (enclosed in square brackets).
"""
function marked_dynkin_diagram(mdt::MarkedDynkinType)
  DT = dynkin_type(mdt)
  marked = marked_nodes(mdt)

  if DT <: SimpleDynkinType
    # D and E types have their own two-dimensional layouts.
    DT <: TypeD && return _marked_diagram_D(DT, marked)
    DT <: TypeE && return _marked_diagram_E(DT, marked)
  end

  diagram = string(dynkin_diagram(DT))
  lines = split(diagram, '\n')
  marked_set = Set(marked)

  if DT <: SimpleDynkinType
    node_line = lines[1]
    result_chars = collect(node_line)
    node_idx = 0
    for (pos, ch) in enumerate(result_chars)
      if ch == '○'
        node_idx += 1
        if node_idx in marked_set
          result_chars[pos] = '×'
        end
      end
    end
    lines[1] = String(result_chars)
    return join(lines, '\n')
  end

  diagram * "\n(marked: $(join(marked, ", ")))"
end

function _marked_diagram_D(::Type{DT}, marked) where {DT<:TypeD}
  N = rank(DT)
  marked_set = Set(marked)
  node_char(i) = i in marked_set ? '×' : '○'

  prefix = " "^(4 * (N - 2)) * "$(node_char(N)) $N"
  fork = " "^(4 * (N - 2) - 1) * "/"
  if N - 1 >= 2
    main = join([string(node_char(i)) for i in 1:(N - 1)], "───")
    main_labels = join([string(i) for i in 1:(N - 1)], "   ")
  else
    main = string(node_char(N - 1))
    main_labels = "$(N - 1)"
  end
  prefix * "\n" * fork * "\n" * main * "\n" * main_labels
end

function _marked_diagram_E(::Type{DT}, marked) where {DT<:TypeE}
  N = rank(DT)
  marked_set = Set(marked)
  node_char(i) = i in marked_set ? '×' : '○'

  main_nodes = [1; 3:N]
  main = join([string(node_char(i)) for i in main_nodes], "───")
  main_labels = join([string(i) for i in main_nodes], "   ")

  indent = 8
  top = " "^indent * "$(node_char(2)) 2"
  branch = " "^indent * "|"
  top * "\n" * branch * "\n" * main * "\n" * main_labels
end

Base.:(==)(a::MarkedDynkinType, b::MarkedDynkinType) =
  dynkin_type(a) == dynkin_type(b) && marked_nodes(a) == marked_nodes(b)

Base.hash(mdt::MarkedDynkinType, h::UInt) = hash((dynkin_type(mdt), marked_nodes(mdt)), h)

"""
    is_exceptional_type(DT::Type{<:DynkinType}) -> Bool

Return `true` if the Dynkin type contains an exceptional simple factor
(``\\mathrm{E}_6``, ``\\mathrm{E}_7``, ``\\mathrm{E}_8``, ``\\mathrm{F}_4``, or ``\\mathrm{G}_2``).

For product types, returns `true` if **any** component is exceptional.
See [`is_exceptional_type(X::PartialFlagVariety)`](@ref) for the note on how
``\\mathrm{G}_2`` varieties are classified.

# Examples
```jldoctest
julia> using PartialFlagVarieties

julia> is_exceptional_type(TypeE{6})
true
```

```jldoctest
julia> using PartialFlagVarieties

julia> is_exceptional_type(ProductDynkinType{Tuple{TypeA{3}, TypeG2}})
true
```
"""
is_exceptional_type(DT::Type{<:SimpleDynkinType}) = DT <: Union{TypeE,TypeF4,TypeG2}
is_exceptional_type(DT::Type{<:ProductDynkinType}) =
  any(is_exceptional_type, DT.parameters[1].parameters)

"""
    is_exceptional_type(mdt::MarkedDynkinType) -> Bool

Return `true` if the ambient Dynkin type of `mdt` contains an exceptional simple
factor (``\\mathrm{E}_6``, ``\\mathrm{E}_7``, ``\\mathrm{E}_8``, ``\\mathrm{F}_4``, or ``\\mathrm{G}_2``).

For product types, returns `true` if **any** component is exceptional.
See [`is_exceptional_type(X::PartialFlagVariety)`](@ref) for the note on how
``\\mathrm{G}_2`` varieties are classified.

# Examples
```jldoctest
julia> using PartialFlagVarieties

julia> mdt = MarkedDynkinType(TypeE{6}, (2,));

julia> is_exceptional_type(mdt)
true
```
"""
is_exceptional_type(mdt::MarkedDynkinType) = is_exceptional_type(dynkin_type(mdt))
